baseurl: "https://rbolt.netlify.app/"
languageCode: "en-us"
title: "Randi Bolt's Website"
theme: "hugo-xmin"
enableEmoji : true
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Contact
      url: "contact/"

params:
  description: "A website built through Hugo and blogdown."
  footer: "Randi Bolt 2021 | [Github](https://github.com/rbolt13)"
markup:
  goldmark:
    renderer:
      unsafe: true
