---
title: "Projects"
date: "8/26/2021"
output: html_document
enableEmoji : true
---

**:ledger: [Personal Website](https://rbolt13.github.io/rsite/index.html)** <br> Summer 2021 - Current<br> _Personal_

* Second blog and first personal website created using blogdown in R studio, and presented through a github repository. The entire website includes examples of elementary coding such as images, hyperlinks, bold and italicized text, headers, centered and indented text, emojis, and a footer signature with link to my Github profile. 

* Quick to construct, approximately one hour is spent weekly making minor adjustments to the overall blog or working on potential or existing posts. 

* Blog posts are shown chronologically on the about page, as well as sorted by tags and category. Currently 6 blog posts are available for viewing. These include include brief tutorials on R studio packages such as Jasmines, and tidy census. Other posts are either mathematical proofs, or micro posts on simple but important mathematical and statistical concepts. 

* The projects page include 10 various projects, including class notes for 3 upper division undergraduate statistics classes. 

* Future blog posts will include examples in R from linear regression analysis, proving least squares estimates, blogdown tutorial, first shiny app, simple shiny tutorial, probability distributions, tree diagrams, Bayes theorem, simple g.i.s., basketball stats, and spotifyr. 

**:pill: [COVID-19](https://rbolt13.github.io/covid19/)** <br> Summer 2021 - Current<br> _Portland State University_

*  Created in R Studio and presented through Github repositories, 6 different data sets from NYT repository along with data from tidycensus package were used to create tables of percentages of  cases, deaths, and vaccinations for states and Oregon couties. 

* The main page includes an interactive table of contents, and an API was used in .Renviron that is ignored by Github. 

* Joined data sets, created columns for calculated percentages, filtered by date, and created "top 5" tables with gt().

* Packages used : magrittr, dplyr, readr, tidyr, lubridate, pander, ggplot2, gt, kableExtra, gridExtra, and tidycenus. 

* Incomplete this site serves as more of a play pen for data and data visual exploration. Future explorations might include shiny. 

**:sunny: [Rsite2](https://rbolt13.github.io/rsite2/)** <br> Summer 2021 <br> _Personal_

* Inspired by riste, rsite2 is another website created using R Studio, and presented on Github. Each page has a different background which was done with some very basic CSS. 

* Images and text with headers are used to show / explain how I created websites like the ones I created for rsite2, rsite, and my class notes. 

* Created a 5 by 13 data frame of classical ballets, and with two visualizations using ggplot(). The first visual is a plot diagram showing ballets in chronological order, showing that La Sylphide is the oldest ballet from 1832, and Alice's Adventures in WonderLand being the newest from 2011. The second visual is a histogram showing that most ballet's have 3 acts with a left skew, and a range of acts from 1 - 4.

* First homework solutions from Statistics - 451 : Applied Statistics for Engineers and Scientists, but done in R Studio. Functions used include : stem(), hist(), mean(), median(), sort(), sum(), length(), sd(), sqrt(), quantile(), min(), max(), par(), and boxplot().

* kableExtra() is used on Home, and Contact page. Tables include hyperlinks and are formatted, and stylized to match backgrounds. A special feature of kableExtra() also allows a row to be highlighted when selected or hovered over by cursur. 

**:herb: [Randi Grows](https://randigrows.netlify.app/about/)** <br> Summer 2021 <br> _Personal_
 
* 

* 

* 

* 

* 

**:chart: [Rsite](https://rbolt13.github.io/rsite/index.html)** <br> Spring 2021 <br> _Portland State University_

* Projects from a 300 level statistics class at Portland State University (STAT 363: Introduction to R) presented through a github repository. 

* Used NYC flight data from nycflights13 library, as well as magrittr, dylyr, pander, tidyr, gt, tidyverse, ggplot2, ggthemes, maps, and lubridate libraries to make tables and a map to answer a couple common travel questions. 

* Analyzed data from Kobe Bryant's performance with the Los Angeles Lakers in the 2009 NBA finals against the Orlando Magic. Then using probability and statistics concepcts such as mean, quantile, conditional probabilities (i.e. Kobe will make a shot given that he made the previous shot), and then compared Kobe's shooting streaks to that of a simulated an independent shooter to find that Kobe did not have a hot hand. 

* Explored how power generated from gas and hydro differed from 2013 and 2017 with data from the Global Power Plant Database. Graphs were made in base R, and ggplot. 

* 11 different COVID-19 data sets between 58 and 3342 observations, and between 9 and 204 variables were used from a Johns Hopkins github repository to analyze states that were highly and mildly impacted by the disease. Wrangled the data into long form, combined multiple data sets, converted date variables into date variables types, tables of average confirmed cases and deaths 90 days before the vaccine and 90 days after, and created graphs to show cases, deaths, and vaccinations, as well as frequency of mask use and opening and closures by state. 

**:green_book: [Oregon Grown : Dispensary Diversity](https://rbolt13.github.io/Oregon-Grown/)** <br> November 2020 - Present <br> _Portland Community College and Portland State University_ 

* Used Spatial references from Oregon Spatial Library, ARLIS,  and PCC Geography Department to apply mapping techniques such as select by attribute, spatial join, clip, and XY Table to Point, to investigate dispensary diversity in Oregon November 2020.

* Formatted, organized, added classifications, and geocoded a data table of about 700 rows of data from the Oregon Liquor Control Commission’s active marijuanna retail license. 

* Discovered more than half of dispensaries in Oregon are owned by a chain and about 10% of the 262 dispensaries in Portland’s Urban Growth Boundary are owned by one chain, Groundworks. 

* Presented virtually at GIS in Action on April 22, 2021. 

* Future plans to investigate dispensaries diversity using R Studio and shiny. 

### Undergrad Notes PSU ~ 

**:bee: [Statistics - 464 : Applied Regression Analysis](https://rbolt13.github.io/stat464/)** <br> Fall 2021 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  _Professor Ge Zhao_  

**Topics Covered :** Simple linear regression, least-square estimates, hypothesis testing, t-statistic, p-statistic, analysis of variance, sum of squares estimate, sum of squares regression, mean square error, confidence intervals, R squared, multiple linear models, hat matrix, Broferoni Method, Scheffe Method, multilinearity, variance inflation factor, model adequacy checking, residual analysis, residual plotting, residual scaling, PRESS statsitic, detecting outliers, transformations and weighting to correct model inadequacies, stabilizing variance, weighted least squares, diagnosstics for leverage and influence, DIFFTS, DFBETAS, and COVRATIO. 

**:ant: [Statistics - 461 : Introduction to Statistics](https://rbolt13.github.io/stat461/)** <br> Fall 2021 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _Professor Dorcas Ofori-Boaten_

**Topics Covered :** Mean, median, mode, variance, standard deviation, the Empirical Rule, basic properties and axioms of probabilities, set theory, DeMorgan's Law, Distributive Law, counting rules, statistical independence, mutual independence, total law of probability, Baye's Rule, discrete and continuous random variables, probability distribution, expected value, CDF, PMF, and PDF. 

**:bug: [Statistics - 451 : Applied Statistics for Engineers and Scientists](https://rbolt13.github.io/stat451/)** <br> Summer 2021 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _Professor Subhash Kochar_

**Topics Covered :** Discrete and continuous random variables and probability distributions, bernoulli random variables, pmf, pdf, expected value, variance, mean, standard deviation for geometric, Poisson, binomial, uniform, exponential, gamma, chi-squared, Weilbull, lognormal, standard beta density curve and normal distributions and r.v.. (This is mainly notes for chapter 3 and 4 of the text)

### Book Notes ~
**:scroll: [An Introduction to Abstract Mathematics (Notes)](https://rbolt13.github.io/itam/)** 

**Topics Covered :** Statements, implications, contrapositives, converse, sets, subsets and collections of sets. 

